### ISSUE TITLE
[Feat] 메인 페이지 전적 리스트 API 데이터 적용 & 스타일 적용

### ISSUE THREAD

**Issue by Jiho31** [hinyc/wanted-codestates-project-10-2#106]
### ISSUE
- Group: client
- Type: feature, style
- Detail: 메인 페이지 전적 리스트 마무리

### TODO
 - [x] 엑박 뜨는 이미지 고치기
 - [x] 맵 이름, 카트 이름, 완주 기록 시간 넣기
 - [x] 드롭다운 빈칸도 마저 채워서 8칸 채워넣기
 - [ ] 스타일 적용
