### ISSUE TITLE
[Feat] 메인화면 그래프 데이터와 연동 및 랭킹 배치 수정

### ISSUE THREAD

**Issue by hinyc** [hinyc/wanted-codestates-project-10-2#112]
### ISSUE
- Group: client, server, sr
- Type: bug, feature, delete
- Detail: fix actions from client redux

### TODO
 - [x] 종합전적 원형그래프 연동
 - [x] 순위변동추이 99, 0 데이터 추가 가공
 - [ ] 탭 트랙 선택시 그래프 데이터 연동
 - [ ] 페이지 하부 배치 수정
