### ISSUE TITLE
종합전적 기록보드 리스트/드롭다운

### ISSUE THREAD

**Issue by Jiho31** [hinyc/wanted-codestates-project-10-2#14]
### TODO
 - [x] 카트 이미지 받아오기
 - [x] 리스트 아이템 컴포넌트 구현
 - [x] 드롭다운 되는 부분 UI 구현
 - [x] 드롭다운 열고 닫기 기능
 - [x] API에서 데이터 받아오기 (?)
 - [ ] #59
