### ISSUE TITLE
[Feat]  네비게이션 바 

### ISSUE THREAD

**Issue by hinyc** [hinyc/wanted-codestates-project-10-2#18]
### ISSUE
- Group: client, 
- Type:  feature
- Detail: 

### TODO
 - [x] 버튼 별 배치 
 - [ ] 메인 아이콘 클릭시 드롭다운메뉴
 - [x] 랭킹클릭시 랭킹페이지로 이동
 - [ ] 나머지머튼 준비중이라고 메시지만 뛰어주기
 - [ ] #62
