### ISSUE TITLE
[Feat] 매칭박스

### ISSUE THREAD

**Issue by hinyc** [hinyc/wanted-codestates-project-10-2#4]
### ISSUE
- Group: client, server, sr
- Type: bug, feature, delete
- Detail: fix actions from client redux

### TODO
 - [x] 전체적인 컴포넌트 마크업 & 스타일링
 - [x] 검색 네비바에 밑에 태그 플레이어 선택시 매치 상대, 카트 나오게 구현 하기
 - [x] 카트 클릭시 티어 설명 모달창 구현하기
 - [x] #67
 - [x] #51
 - [ ] #79
