### ISSUE TITLE
[Feat] 페이지별 컴포넌트 스타일 수정

### ISSUE THREAD

**Issue by yong313** [hinyc/wanted-codestates-project-10-2#55]
### ISSUE
- Group: client, server, sr
- Type: bug, feature, delete
- Detail: fix actions from client redux

### TODO
 - [x] 각 페이지별 컴포넌트 스타일 수정
 - [x] 모달 백그라운드 스크롤 막기
 - [x] 도넛차트 호버 시 tooltip 막기
 - [x] 트랙 전적 차트 추가
