### ISSUE TITLE
api 데이터 가공해서 메인페이지 전적 리스트에 넣기

### ISSUE THREAD

**Issue by Jiho31** [hinyc/wanted-codestates-project-10-2#59]
### TODO
 - [x] 데이터 가공하기
 - [x] 리스트에 맞게 넣기 
 - [ ] 데이터 이용해서 게임 완주 기록 시간 계산하는 알고리즘 짜기
 - [ ] 매치 플레이한 날짜 계산하기 (오늘로부터 몇 시간/며칠 전인지)
 - [ ] api 가져올 때 로딩 스피너 넣기
