### ISSUE TITLE
[Feat] 통합 / 매우빠름 / 무한부스터 서브 네비바 컴포넌트 구현

### ISSUE THREAD

**Issue by yong313** [hinyc/wanted-codestates-project-10-2#74]
### ISSUE
- Group: client, server, sr
- Type: bug, feature, delete
- Detail: fix actions from client redux

### TODO
 - [x] 통합 / 매우빠름 / 무한부스터 서브 네비바 컴포넌트 구현
 - [x] 레코드 리스트 컨테이너 컴포넌트 통합 페이지로 이동
 - [ ] 빈 페이지 에니메이션 추가
